# Generated by Django 5.0.1 on 2026-03-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Editions Recréation', max_length=120, verbose_name='Nom du site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/%Y/%m/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/%Y/%m/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#F5F1E8', max_length=20, verbose_name='Couleur primaire')),
                ('accent_color', models.CharField(default='#0A18FF', max_length=20, verbose_name='Couleur accent')),
                ('accent_dark', models.CharField(default='#001FD8', max_length=20, verbose_name='Couleur accent foncée')),
                ('text_color', models.CharField(default='#2C2C2C', max_length=20, verbose_name='Couleur texte')),
                ('text_light', models.CharField(default='#4A4A4A', max_length=20, verbose_name='Couleur texte secondaire')),
                ('light_bg', models.CharField(default='#F9F7F3', max_length=20, verbose_name='Fond clair')),
                ('dark_bg', models.CharField(default='#2C2C2C', max_length=20, verbose_name='Fond foncé')),
                ('font_heading', models.CharField(blank=True, help_text="Ex: 'Cormorant Garamond', serif", max_length=120, verbose_name='Police titres')),
                ('font_body', models.CharField(blank=True, help_text="Ex: 'Source Serif 4', serif", max_length=120, verbose_name='Police texte')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('x_twitter', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Apparence du site',
                'verbose_name_plural': 'Apparence du site',
            },
        ),
    ]
