# Generated by Django 5.0.1 on 2026-03-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_siteappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='audio_payment_url',
            field=models.URLField(blank=True, verbose_name='Lien de paiement (conversion texte en audio)'),
        ),
    ]
