# Generated by Django 5.0.1 on 2026-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteappearance_site_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='audio_payment_url_1',
            field=models.URLField(blank=True, verbose_name='Paiement audio (1 à 100 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='audio_payment_url_2',
            field=models.URLField(blank=True, verbose_name='Paiement audio (101 à 200 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='audio_payment_url_3',
            field=models.URLField(blank=True, verbose_name='Paiement audio (201 à 500 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='audio_payment_url_4',
            field=models.URLField(blank=True, verbose_name='Paiement audio (501 à 1000 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='audio_payment_url_5',
            field=models.URLField(blank=True, verbose_name='Paiement audio (1001+ pages)'),
        ),
    ]
