# Generated by Django 5.0.1 on 2026-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteappearance_audio_payment_url_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_audio_product_id_1',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chariow produit (1 à 100 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_audio_product_id_2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chariow produit (101 à 200 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_audio_product_id_3',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chariow produit (201 à 500 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_audio_product_id_4',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chariow produit (501 à 1000 pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_audio_product_id_5',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chariow produit (1001+ pages)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20, verbose_name='Chariow - Couleur fond'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_border_style',
            field=models.CharField(blank=True, default='rounded', max_length=20, verbose_name='Chariow - Bordure'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_cta_animation',
            field=models.CharField(blank=True, default='none', max_length=40, verbose_name='Chariow - Animation CTA'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_cta_width',
            field=models.CharField(blank=True, default='xs', max_length=20, verbose_name='Chariow - Largeur CTA'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_locale',
            field=models.CharField(blank=True, default='fr', max_length=20, verbose_name='Chariow - Langue'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_primary_color',
            field=models.CharField(blank=True, default='#0000ff', max_length=20, verbose_name='Chariow - Couleur primaire'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_store_domain',
            field=models.CharField(blank=True, help_text='Ex: recreation.mychariow.shop', max_length=255, verbose_name='Chariow - Domaine boutique'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='chariow_style',
            field=models.CharField(blank=True, default='tap', max_length=20, verbose_name='Chariow - Style'),
        ),
    ]
