# Generated by Codex on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_siteappearance_chariow_widget_code_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteappearance",
            name="audio_human_payment_url",
            field=models.URLField(blank=True, verbose_name="Lien de paiement (voix humaine)"),
        ),
        migrations.AddField(
            model_name="siteappearance",
            name="audio_human_payment_url_1",
            field=models.URLField(blank=True, verbose_name="Paiement voix humaine (1 à 100 pages)"),
        ),
        migrations.AddField(
            model_name="siteappearance",
            name="audio_human_payment_url_2",
            field=models.URLField(blank=True, verbose_name="Paiement voix humaine (101 à 200 pages)"),
        ),
        migrations.AddField(
            model_name="siteappearance",
            name="audio_human_payment_url_3",
            field=models.URLField(blank=True, verbose_name="Paiement voix humaine (201 à 500 pages)"),
        ),
        migrations.AddField(
            model_name="siteappearance",
            name="audio_human_payment_url_4",
            field=models.URLField(blank=True, verbose_name="Paiement voix humaine (501 à 1000 pages)"),
        ),
        migrations.AddField(
            model_name="siteappearance",
            name="audio_human_payment_url_5",
            field=models.URLField(blank=True, verbose_name="Paiement voix humaine (1001+ pages)"),
        ),
    ]
