# Generated by Django 5.0.1 on 2026-03-29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_siteappearance_tts_acronyms"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "default_meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Titre SEO utilise si une page ne definit pas son propre titre.",
                        max_length=120,
                        verbose_name="Titre SEO par defaut",
                    ),
                ),
                (
                    "default_meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Description SEO utilisee si une page ne definit pas sa propre description.",
                        max_length=200,
                        verbose_name="Description SEO par defaut",
                    ),
                ),
                (
                    "default_canonical",
                    models.URLField(
                        blank=True,
                        help_text="URL canonical globale si une page ne definit pas la sienne.",
                        verbose_name="Canonical par defaut",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/%Y/%m/",
                        verbose_name="Image OpenGraph",
                    ),
                ),
                (
                    "newsletter_title",
                    models.CharField(
                        blank=True,
                        default="Abonnez-vous a la newsletter",
                        max_length=160,
                        verbose_name="Titre newsletter",
                    ),
                ),
                (
                    "newsletter_subtitle",
                    models.CharField(
                        blank=True,
                        default="Recevez nos actualites et nouveautes.",
                        max_length=240,
                        verbose_name="Sous-titre newsletter",
                    ),
                ),
                (
                    "newsletter_placeholder",
                    models.CharField(
                        blank=True,
                        default="Votre email",
                        max_length=120,
                        verbose_name="Placeholder newsletter",
                    ),
                ),
                (
                    "newsletter_button_label",
                    models.CharField(
                        blank=True,
                        default="Newsletter",
                        max_length=80,
                        verbose_name="Libelle bouton newsletter",
                    ),
                ),
                (
                    "footer_slogan",
                    models.TextField(
                        blank=True,
                        default="Avec le verbe, recreons le monde et conservons en une copie dans un livre !",
                        verbose_name="Slogan pied de page",
                    ),
                ),
                (
                    "footer_address",
                    models.TextField(
                        blank=True,
                        default=(
                            "Nous sommes au Benin, Abomey-Calavi et nous avons des representants "
                            "editoriaux en France, Marseille et dans 7 autres pays en Afrique."
                        ),
                        verbose_name="Adresse pied de page",
                    ),
                ),
                (
                    "footer_copyright",
                    models.CharField(
                        blank=True,
                        default="Editions Recreation - Tous droits reserves",
                        max_length=200,
                        verbose_name="Mention copyright",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenu du site",
                "verbose_name_plural": "Contenus du site",
            },
        ),
    ]
