# Generated by Codex on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_siteappearance_audio_human_payment_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteappearance",
            name="audio_human_payment_url_6",
            field=models.URLField(blank=True, verbose_name="Paiement voix humaine (1001+ pages)"),
        ),
    ]
