# Generated by Codex on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_siteappearance_audio_human_payment_url_6"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("header_search_placeholder", models.CharField(blank=True, default="Rechercher des livres, auteurs, actualités...", max_length=200, verbose_name="Placeholder recherche")),
                ("header_search_button", models.CharField(blank=True, default="Chercher", max_length=60, verbose_name="Bouton recherche")),
                ("newsletter_placeholder", models.CharField(blank=True, default="Votre email", max_length=120, verbose_name="Placeholder newsletter")),
                ("newsletter_button_label", models.CharField(blank=True, default="Bulletin", max_length=80, verbose_name="Bouton newsletter")),
                ("nav_menu_label", models.CharField(blank=True, default="Menu", max_length=40, verbose_name="Label bouton menu")),
                ("nav_drawer_title", models.CharField(blank=True, default="Menu", max_length=80, verbose_name="Titre menu mobile")),
                ("nav_drawer_social_title", models.CharField(blank=True, default="Suivez Recréation sur les réseaux sociaux", max_length=120, verbose_name="Titre réseaux sociaux (mobile)")),
                ("nav_drawer_shop_label", models.CharField(blank=True, default="Recréation Shop", max_length=80, verbose_name="Label shop (mobile)")),
                ("nav_cta_title", models.CharField(blank=True, default="Abonnez-vous à la newsletter", max_length=120, verbose_name="Titre CTA menu")),
                ("nav_cta_text", models.CharField(blank=True, default="Recevez nos actualités et nouveautés.", max_length=200, verbose_name="Texte CTA menu")),
                ("nav_cta_button", models.CharField(blank=True, default="S'abonner", max_length=60, verbose_name="Bouton CTA menu")),
                ("footer_slogan", models.CharField(blank=True, default="Avec le verbe, recréons le monde et conservons en une copie dans un livre !", max_length=200, verbose_name="Slogan footer")),
                ("footer_address", models.CharField(blank=True, default="Bénin | Abomey-Calavi, France | Marseille, avec des Représentants éditoriaux dans 7 autres pays en Afrique.", max_length=240, verbose_name="Adresse footer")),
                ("footer_action_phone_label", models.CharField(blank=True, default="Téléphone", max_length=60, verbose_name="Label action téléphone")),
                ("footer_action_submit_label", models.CharField(blank=True, default="Soumettre un manuscrit", max_length=80, verbose_name="Label action soumission")),
                ("footer_action_email_label", models.CharField(blank=True, default="E-mail", max_length=60, verbose_name="Label action email")),
                ("footer_social_title", models.CharField(blank=True, default="Nous suivre les réseaux sociaux", max_length=120, verbose_name="Titre réseaux sociaux (footer)")),
                ("footer_catalogue_title", models.CharField(blank=True, default="Catalogue", max_length=80, verbose_name="Titre colonne Catalogue")),
                ("footer_collections_title", models.CharField(blank=True, default="Collections", max_length=80, verbose_name="Titre collections")),
                ("footer_audio_cta_label", models.CharField(blank=True, default="Conversion de texte en audio", max_length=120, verbose_name="CTA audio")),
                ("footer_shop_cta_label", models.CharField(blank=True, default="Recréation Shop", max_length=80, verbose_name="CTA shop")),
                ("footer_resources_title", models.CharField(blank=True, default="Ressources", max_length=80, verbose_name="Titre colonne Ressources")),
                ("footer_contact_link_label", models.CharField(blank=True, default="Nous contacter", max_length=80, verbose_name="Lien Nous contacter")),
                ("footer_copyright_text", models.CharField(blank=True, default="Editions Recréation - Tous droits réservés - 2026", max_length=200, verbose_name="Copyright")),
            ],
            options={
                "verbose_name": "Contenu du site",
                "verbose_name_plural": "Contenu du site",
            },
        ),
    ]
