# Generated by Django 5.0.1 on 2026-03-29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_sitecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="nav_title_collections",
            field=models.CharField(max_length=120, blank=True, default="Collections", verbose_name="Navigation - Titre collections"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="nav_title_formats",
            field=models.CharField(max_length=120, blank=True, default="Autres versions de livres", verbose_name="Navigation - Titre formats"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="nav_title_services",
            field=models.CharField(max_length=120, blank=True, default="Autres services", verbose_name="Navigation - Titre services"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="nav_menu_label",
            field=models.CharField(max_length=80, blank=True, default="Menu", verbose_name="Navigation - Libelle bouton menu"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="nav_cta_title",
            field=models.CharField(max_length=160, blank=True, default="Abonnez-vous a la newsletter", verbose_name="Navigation - Titre newsletter"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="nav_cta_text",
            field=models.CharField(max_length=240, blank=True, default="Recevez nos actualites et nouveautes.", verbose_name="Navigation - Texte newsletter"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="nav_cta_button",
            field=models.CharField(max_length=80, blank=True, default="S'abonner", verbose_name="Navigation - Bouton newsletter"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="header_search_placeholder",
            field=models.CharField(max_length=160, blank=True, default="Rechercher livres, auteurs, actualites...", verbose_name="Header - Placeholder recherche"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="header_search_button",
            field=models.CharField(max_length=80, blank=True, default="Rechercher", verbose_name="Header - Bouton recherche"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_title_catalogue",
            field=models.CharField(max_length=120, blank=True, default="Catalogue", verbose_name="Footer - Titre catalogue"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_title_collections",
            field=models.CharField(max_length=120, blank=True, default="Collections", verbose_name="Footer - Titre collections"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_title_resources",
            field=models.CharField(max_length=120, blank=True, default="Ressources", verbose_name="Footer - Titre ressources"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_title_services",
            field=models.CharField(max_length=120, blank=True, default="Services", verbose_name="Footer - Titre services"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_social_title",
            field=models.CharField(max_length=160, blank=True, default="Nous suivre les reseaux sociaux", verbose_name="Footer - Titre reseaux sociaux"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_catalogue_label",
            field=models.CharField(max_length=120, blank=True, default="Catalogue", verbose_name="Footer - Libelle catalogue"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_catalogue_news_label",
            field=models.CharField(max_length=120, blank=True, default="Nouveautes", verbose_name="Footer - Libelle nouveautes"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_catalogue_upcoming_label",
            field=models.CharField(max_length=120, blank=True, default="Prochaines parutions", verbose_name="Footer - Libelle prochaines parutions"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_action_phone_label",
            field=models.CharField(max_length=120, blank=True, default="Telephone", verbose_name="Footer - Libelle telephone"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_action_submit_label",
            field=models.CharField(max_length=160, blank=True, default="Soumettez votre manuscrit/tapuscrit", verbose_name="Footer - Libelle soumission"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_action_email_label",
            field=models.CharField(max_length=120, blank=True, default="E-mail", verbose_name="Footer - Libelle email"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_action_conversion_label",
            field=models.CharField(max_length=160, blank=True, default="Conversion de texte en audio", verbose_name="Footer - Libelle conversion audio"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="footer_action_shop_label",
            field=models.CharField(max_length=120, blank=True, default="Recreation Shop", verbose_name="Footer - Libelle boutique"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_hero_note",
            field=models.TextField(blank=True, default="Collez votre texte ou televersez un fichier. Le service est gratuit pour les textes de 5000 caracteres maximum. Les fichiers televerses sont systematiquement soumis au paiement. Apres paiement, nous produisons l'audio et vous l'envoyons par e-mail.", verbose_name="Conversion - Texte d'introduction"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_free_limit_text",
            field=models.CharField(max_length=200, blank=True, default="Le service est gratuit pour les textes de 5000 caracteres maximum.", verbose_name="Conversion - Message limite gratuite"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_file_payment_text",
            field=models.CharField(max_length=200, blank=True, default="Les fichiers televerses sont systematiquement soumis au paiement.", verbose_name="Conversion - Message fichier payant"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_formats_text",
            field=models.CharField(max_length=200, blank=True, default="Formats pris en charge : txt, docx, pdf, jpg, png, pptx, xlsx, epub.", verbose_name="Conversion - Message formats"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_form_title",
            field=models.CharField(max_length=160, blank=True, default="Convertissez votre texte ici", verbose_name="Conversion - Titre formulaire"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_payment_note_text",
            field=models.CharField(max_length=200, blank=True, default="Le texte depasse la longueur autorisee en mode gratuit : payez un montant forfaitaire pour ce service.", verbose_name="Conversion - Note paiement"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_payment_required_title",
            field=models.CharField(max_length=160, blank=True, default="Paiement requis", verbose_name="Conversion - Titre paiement requis"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_payment_required_text",
            field=models.CharField(max_length=240, blank=True, default="Votre demande a ete enregistree. Veuillez proceder au paiement pour recevoir l'audio par e-mail.", verbose_name="Conversion - Texte paiement requis"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_payment_error_text",
            field=models.CharField(max_length=200, blank=True, default="Impossible de lancer le paiement. Veuillez reessayer ou nous contacter.", verbose_name="Conversion - Erreur paiement"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_processing_title",
            field=models.CharField(max_length=160, blank=True, default="Votre demande est en cours de traitement", verbose_name="Conversion - Titre traitement"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_processing_text",
            field=models.CharField(max_length=200, blank=True, default="Nos equipes verifieront l'effectivite du paiement et vous feront un retour.", verbose_name="Conversion - Texte traitement"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_progress_title",
            field=models.CharField(max_length=160, blank=True, default="Conversion en cours", verbose_name="Conversion - Titre progression"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_progress_text",
            field=models.CharField(max_length=200, blank=True, default="Votre audio est en preparation. Cette page se mettra a jour automatiquement.", verbose_name="Conversion - Texte progression"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_audio_ready_title",
            field=models.CharField(max_length=160, blank=True, default="Votre audio est pret", verbose_name="Conversion - Titre audio pret"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_audio_download_label",
            field=models.CharField(max_length=160, blank=True, default="Telecharger l'audio (MP3)", verbose_name="Conversion - Bouton telechargement"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_unavailable_free_text",
            field=models.CharField(max_length=240, blank=True, default="Service momentanement indisponible. Veuillez reessayer plus tard ou essayez avec une version payante.", verbose_name="Conversion - Indisponibilite gratuite"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_unavailable_paid_text",
            field=models.CharField(max_length=240, blank=True, default="Le service payant est momentanement indisponible. Essayez un depot de fichiers ou la lecture par un humain.", verbose_name="Conversion - Indisponibilite payante"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_free_limit_reached_text",
            field=models.CharField(max_length=240, blank=True, default="Vous avez atteint la limite de conversion gratuite quotidienne.", verbose_name="Conversion - Limite gratuite atteinte"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_limit_cta_paid_label",
            field=models.CharField(max_length=160, blank=True, default="Essayer la version payante", verbose_name="Conversion - Bouton version payante"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_limit_cta_human_label",
            field=models.CharField(max_length=160, blank=True, default="Lecture par un humain", verbose_name="Conversion - Bouton lecture humaine"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_title",
            field=models.CharField(max_length=160, blank=True, default="Conversion de texte en audio", verbose_name="Choix conversion - Titre"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_subtitle",
            field=models.CharField(max_length=240, blank=True, default="Choisissez le type de conversion qui vous convient : synthetique ou lecture humaine.", verbose_name="Choix conversion - Sous-titre"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_synth_title",
            field=models.CharField(max_length=160, blank=True, default="Conversion synthetique", verbose_name="Choix conversion - Titre synthetique"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_synth_text",
            field=models.CharField(max_length=240, blank=True, default="Conversion rapide par voix synthetique, gratuite jusqu'a 5000 caracteres.", verbose_name="Choix conversion - Texte synthetique"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_synth_button",
            field=models.CharField(max_length=160, blank=True, default="Continuer en synthetique", verbose_name="Choix conversion - Bouton synthetique"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_human_title",
            field=models.CharField(max_length=160, blank=True, default="Lecture par un humain", verbose_name="Choix conversion - Titre humain"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_human_text",
            field=models.CharField(max_length=240, blank=True, default="Confiez votre texte a un membre de notre equipe pour une lecture par un humain.", verbose_name="Choix conversion - Texte humain"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="conversion_choice_human_button",
            field=models.CharField(max_length=200, blank=True, default="Continuer en lecture par un humain", verbose_name="Choix conversion - Bouton humain"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="activation_email_subject",
            field=models.CharField(max_length=160, blank=True, default="Confirmez votre compte", verbose_name="Email - Sujet activation"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="activation_email_body",
            field=models.TextField(blank=True, default="Bonjour {first_name}\n\nMerci de confirmer votre compte en cliquant sur ce lien :\n{activation_link}\n\nEditions Recreation", verbose_name="Email - Corps activation"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="activation_success_message",
            field=models.CharField(max_length=200, blank=True, default="Votre compte est active. Vous pouvez utiliser le service.", verbose_name="Message - Activation reussie"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="activation_invalid_message",
            field=models.CharField(max_length=200, blank=True, default="Lien d'activation invalide ou expire.", verbose_name="Message - Activation invalide"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="signup_success_message",
            field=models.CharField(max_length=240, blank=True, default="Compte cree. Un email de confirmation vous a ete envoye. Activez votre compte pour continuer.", verbose_name="Message - Inscription reussie"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="error_404_title",
            field=models.CharField(max_length=160, blank=True, default="Page introuvable", verbose_name="Erreur 404 - Titre"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="error_404_text",
            field=models.TextField(blank=True, default="La page demandee est introuvable. Revenez a l'accueil ou utilisez la recherche.", verbose_name="Erreur 404 - Texte"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="error_500_title",
            field=models.CharField(max_length=160, blank=True, default="Une erreur est survenue", verbose_name="Erreur 500 - Titre"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="error_500_text",
            field=models.TextField(blank=True, default="Une erreur interne est survenue. Veuillez reessayer plus tard.", verbose_name="Erreur 500 - Texte"),
        ),
    ]
