# Generated by Django 5.2.8 on 2026-03-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sitecontent_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='audio_human_payment_url_1',
            field=models.URLField(blank=True, verbose_name='Paiement voix humaine (1 à 50 pages)'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='audio_human_payment_url_2',
            field=models.URLField(blank=True, verbose_name='Paiement voix humaine (51 à 100 pages)'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='audio_human_payment_url_3',
            field=models.URLField(blank=True, verbose_name='Paiement voix humaine (101 à 200 pages)'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='audio_human_payment_url_4',
            field=models.URLField(blank=True, verbose_name='Paiement voix humaine (201 à 500 pages)'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='audio_human_payment_url_5',
            field=models.URLField(blank=True, verbose_name='Paiement voix humaine (501 à 1000 pages)'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='site_meta_keywords',
            field=models.CharField(blank=True, help_text='Mots-cl?s s?par?s par des virgules pour le site', max_length=255, verbose_name='Mots-cl?s SEO (site)'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='a_propos_meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Meta keywords ? propos'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='actualites_meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Meta keywords Actualit?s'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_brand_subtitle',
            field=models.CharField(blank=True, default='Membres du Comit? de lecture', max_length=160, verbose_name='Comit? - Sous-titre marque'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_brand_title',
            field=models.CharField(blank=True, default='Editions Recr?ation', max_length=120, verbose_name='Comit? - Titre marque'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_text_primary',
            field=models.CharField(blank=True, default='Connectez-vous pour acc?der ? l?espace des membres du Comit? de lecture.', max_length=220, verbose_name='Comit? - Texte connexion 1'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_text_secondary',
            field=models.CharField(blank=True, default='Si vous n?avez pas encore un compte ?valuateur, inscrivez-vous.', max_length=200, verbose_name='Comit? - Texte connexion 2'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_title',
            field=models.CharField(blank=True, default='Connexion', max_length=80, verbose_name='Comit? - Titre connexion'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_confidentiality_text',
            field=models.TextField(blank=True, default='Votre inscription implique votre accord pour garantir la confidentialit? des donn?es personnelles de nos auteurs et de tous les fichiers dont vous auriez connaissance, afin d?emp?cher toute divulgation ? des tiers. Les fichiers t?l?charg?s lors de l??valuation des dossiers d??dition ne doivent en aucun cas ?tre conserv?s. La suppression est imp?rative dans un d?lai inf?rieur ? une semaine. Prenez-vous acte de ces dispositions et consentez-vous ? en respecter strictement toutes les clauses ?', verbose_name='Comit? - Texte confidentialit?'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_intro',
            field=models.TextField(blank=True, default="Veuillez compl?ter ce formulaire afin de soumettre votre demande d'acc?s. Votre demande fera l'objet d'une analyse par un administrateur. Une fois la conformit? de votre profil ? nos crit?res valid?e, votre compte sera activ?.", verbose_name='Comit? - Introduction inscription'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_motivation_label',
            field=models.CharField(blank=True, default='Qu?est-ce qui vous motive ? rejoindre l??quipe des membres du Comit? de lecture des ?ditions Recr?ation ?', max_length=220, verbose_name='Comit? - Question motivation'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_submit_label',
            field=models.CharField(blank=True, default='Envoyer la demande', max_length=80, verbose_name='Comit? - Bouton inscription'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_title',
            field=models.CharField(blank=True, default='Inscription ?valuateur', max_length=120, verbose_name='Comit? - Titre inscription'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_unpaid_label',
            field=models.CharField(blank=True, default='Cette mission n?est pas r?mun?r?e. En avez-vous conscience et ?tes-vous toujours partant pour nous rejoindre ?', max_length=200, verbose_name='Comit? - Question mission non r?mun?r?e'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='default_meta_description',
            field=models.TextField(blank=True, default="Editions Recr?ation, maison d'?dition g?n?raliste. D?couvrez nos livres papier, num?riques et audio.", max_length=200, verbose_name='Meta description par d?faut'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='default_meta_keywords',
            field=models.CharField(blank=True, default='', help_text='Mots-cl?s s?par?s par des virgules', max_length=255, verbose_name='Meta keywords par d?faut'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='default_meta_title',
            field=models.CharField(blank=True, default="Editions Recr?ation - Maison d'?dition g?n?raliste", max_length=120, verbose_name='Meta title par d?faut'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='Editions Recr?ation - Tous droits r?serv?s - 2026', max_length=200, verbose_name='Copyright'),
        ),
    ]
