# Generated by Django 5.2.8 on 2026-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_siteappearance_audio_human_payment_url_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='site_meta_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules pour le site', max_length=255, verbose_name='Mots-clés SEO (site)'),
        ),
    ]
