# Generated by ChatGPT on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_siteappearance_site_meta_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="newsletter_message_success",
            field=models.CharField(
                blank=True,
                default="Merci ! Vous êtes inscrit à notre newsletter.",
                max_length=200,
                verbose_name="Newsletter - succès",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="newsletter_message_reactivated",
            field=models.CharField(
                blank=True,
                default="Votre inscription a été réactivée.",
                max_length=200,
                verbose_name="Newsletter - réactivation",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="newsletter_message_already",
            field=models.CharField(
                blank=True,
                default="Vous êtes déjà inscrit.",
                max_length=200,
                verbose_name="Newsletter - déjà inscrit",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="newsletter_message_error",
            field=models.CharField(
                blank=True,
                default="Une erreur s'est produite. Veuillez vérifier votre email.",
                max_length=200,
                verbose_name="Newsletter - erreur",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="newsletter_message_invalid",
            field=models.CharField(
                blank=True,
                default="Veuillez saisir une adresse email valide.",
                max_length=200,
                verbose_name="Newsletter - email invalide",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="contact_message_success",
            field=models.CharField(
                blank=True,
                default="Votre message a été envoyé avec succès ! Nous vous répondrons dans les plus brefs délais.",
                max_length=240,
                verbose_name="Contact - succès",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="contact_message_error",
            field=models.CharField(
                blank=True,
                default="Une erreur s'est produite. Veuillez vérifier les informations saisies.",
                max_length=200,
                verbose_name="Contact - erreur",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="contact_message_missing",
            field=models.CharField(
                blank=True,
                default="Veuillez remplir tous les champs obligatoires.",
                max_length=200,
                verbose_name="Contact - champs manquants",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="soumission_message_success",
            field=models.CharField(
                blank=True,
                default="Merci ! Votre manuscrit a été soumis avec succès. Nous vous contacterons rapidement.",
                max_length=240,
                verbose_name="Soumission - succès",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="soumission_message_error",
            field=models.CharField(
                blank=True,
                default="Une erreur s'est produite. Veuillez vérifier les informations saisies.",
                max_length=200,
                verbose_name="Soumission - erreur",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="committee_signup_success",
            field=models.CharField(
                blank=True,
                default="Votre demande a été envoyée. Un administrateur doit l’approuver.",
                max_length=200,
                verbose_name="Comité - demande envoyée",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="committee_review_saved",
            field=models.CharField(
                blank=True,
                default="Évaluation enregistrée.",
                max_length=120,
                verbose_name="Comité - évaluation enregistrée",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="audio_message_success",
            field=models.CharField(
                blank=True,
                default="Votre audio est prêt. Vous pouvez l'écouter en cliquant sur play. Vous pouvez aussi le télécharger gratuitement.",
                max_length=260,
                verbose_name="Audio - prêt",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="audio_message_failed",
            field=models.CharField(
                blank=True,
                default="La génération de l’audio a échoué. Veuillez réessayer.",
                max_length=200,
                verbose_name="Audio - échec",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="audio_message_not_ready",
            field=models.CharField(
                blank=True,
                default="La génération de l’audio n’a pas abouti. Veuillez réessayer.",
                max_length=200,
                verbose_name="Audio - non abouti",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="audio_payment_pending_message",
            field=models.CharField(
                blank=True,
                default="Merci. Nous allons vérifier votre paiement et vous contacter très rapidement par e-mail.",
                max_length=240,
                verbose_name="Audio - paiement à vérifier",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="account_signup_success",
            field=models.CharField(
                blank=True,
                default="Compte créé. Un email de confirmation vous a été envoyé. Activez votre compte pour continuer.",
                max_length=240,
                verbose_name="Compte - création",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="account_activation_success",
            field=models.CharField(
                blank=True,
                default="Votre compte est activé. Vous pouvez utiliser le service.",
                max_length=200,
                verbose_name="Compte - activation ok",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="account_activation_invalid",
            field=models.CharField(
                blank=True,
                default="Lien d’activation invalide ou expiré.",
                max_length=200,
                verbose_name="Compte - activation invalide",
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="account_login_invalid",
            field=models.CharField(
                blank=True,
                default="Identifiants invalides.",
                max_length=120,
                verbose_name="Compte - identifiants invalides",
            ),
        ),
    ]

