# Generated by ChatGPT on 2026-04-01

from django.db import migrations
from html import unescape


def _normalize_text_value(value):
    if value is None:
        return value
    if not isinstance(value, str):
        return value
    text = unescape(value)
    replacements = {
        "ÃƒÂ©": "é",
        "ÃƒÂ¨": "è",
        "ÃƒÂª": "ê",
        "ÃƒÂ«": "ë",
        "ÃƒÂ ": "à",
        "ÃƒÂ¢": "â",
        "ÃƒÂ®": "î",
        "ÃƒÂ´": "ô",
        "ÃƒÂ¹": "ù",
        "ÃƒÂ»": "û",
        "ÃƒÂ§": "ç",
        "Ãƒâ€°": "É",
        "Ãƒâ‚¬": "À",
        "Ã¢â‚¬â„¢": "’",
        "Ã¢â‚¬Å“": "“",
        "Ã¢â‚¬Â": "”",
        "Ã¢â‚¬â€œ": "–",
        "Ã¢â‚¬â€": "—",
        "Ã‚": "",
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)
    return text


def normalize_core_texts(apps, schema_editor):
    for model in apps.get_models():
        if model._meta.app_label != "core":
            continue
        fields = [
            f
            for f in model._meta.fields
            if f.get_internal_type() in ("CharField", "TextField")
            and f.get_internal_type() not in ("EmailField", "URLField", "SlugField")
        ]
        if not fields:
            continue
        for obj in model.objects.all():
            updated = False
            for field in fields:
                value = getattr(obj, field.name, None)
                if isinstance(value, str) and value:
                    cleaned = _normalize_text_value(value)
                    if cleaned != value:
                        setattr(obj, field.name, cleaned)
                        updated = True
            if updated:
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_sitecontent_notifications"),
    ]

    operations = [
        migrations.RunPython(normalize_core_texts, migrations.RunPython.noop),
    ]

