# Generated by Django 5.2.8 on 2026-04-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_normalize_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='a_propos_meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Meta keywords A propos'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='actualites_meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Meta keywords Actualités'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_brand_subtitle',
            field=models.CharField(blank=True, default='Membres du Comite de lecture', max_length=160, verbose_name='Comite - Sous-titre marque'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_brand_title',
            field=models.CharField(blank=True, default='Editions Recreation', max_length=120, verbose_name='Comite - Titre marque'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_text_primary',
            field=models.CharField(blank=True, default="Connectez-vous pour acceder a l'espace des membres du Comite de lecture.", max_length=220, verbose_name='Comite - Texte connexion 1'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_text_secondary',
            field=models.CharField(blank=True, default="Si vous n'avez pas encore un compte evaluateur, inscrivez-vous.", max_length=200, verbose_name='Comite - Texte connexion 2'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_login_title',
            field=models.CharField(blank=True, default='Connexion', max_length=80, verbose_name='Comite - Titre connexion'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_confidentiality_text',
            field=models.TextField(blank=True, default="Votre inscription implique votre accord pour garantir la confidentialite des donnees personnelles de nos auteurs et de tous les fichiers dont vous auriez connaissance, afin d'empecher toute divulgation a des tiers. Les fichiers telecharges lors de l'evaluation des dossiers d'edition ne doivent en aucun cas etre conserves. La suppression est imperative dans un delai inferieur a une semaine. Prenez-vous acte de ces dispositions et consentez-vous a en respecter strictement toutes les clauses ?", verbose_name='Comite - Texte confidentialite'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_intro',
            field=models.TextField(blank=True, default="Veuillez completer ce formulaire afin de soumettre votre demande d'acces. Votre demande fera l'objet d'une analyse par un administrateur. Une fois la conformite de votre profil a nos criteres validee, votre compte sera active.", verbose_name='Comite - Introduction inscription'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_motivation_label',
            field=models.CharField(blank=True, default="Qu'est-ce qui vous motive a rejoindre l'equipe des membres du Comite de lecture des editions Recreation ?", max_length=220, verbose_name='Comite - Question motivation'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_submit_label',
            field=models.CharField(blank=True, default='Envoyer la demande', max_length=80, verbose_name='Comité - Bouton inscription'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_title',
            field=models.CharField(blank=True, default='Inscription evaluateur', max_length=120, verbose_name='Comite - Titre inscription'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='committee_signup_unpaid_label',
            field=models.CharField(blank=True, default="Cette mission n'est pas remuneree. En avez-vous conscience et etes-vous toujours partant pour nous rejoindre ?", max_length=200, verbose_name='Comite - Question mission non remuneree'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='contact_phone_display',
            field=models.CharField(blank=True, default='(+229) 01 68 80 97 77', max_length=60, verbose_name='Téléphone affiche'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='contact_phone_label',
            field=models.CharField(blank=True, default='Telephone', max_length=80, verbose_name='Label telephone'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='default_meta_description',
            field=models.TextField(blank=True, default="Editions Recréation, maison d'édition généraliste. Découvrez nos livres papier, numériques et audio.", max_length=200, verbose_name='Meta description par défaut'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='default_meta_keywords',
            field=models.CharField(blank=True, default='', help_text='Mots-clés séparés par des virgules', max_length=255, verbose_name='Meta keywords par défaut'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='default_meta_title',
            field=models.CharField(blank=True, default="Editions Recréation - Maison d'édition généraliste", max_length=120, verbose_name='Meta title par défaut'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='Editions Recréation - Tous droits réservés - 2026', max_length=200, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='footer_link_confidentialite',
            field=models.CharField(blank=True, default='Confidentialité', max_length=120, verbose_name='Lien confidentialité'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='footer_link_mentions',
            field=models.CharField(blank=True, default='Mentions legales', max_length=120, verbose_name='Lien mentions'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='footer_link_rejoindre_comite',
            field=models.CharField(blank=True, default='Rejoindre notre Comité de lecture', max_length=200, verbose_name='Lien comité lecture'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='nav_drawer_committee_label',
            field=models.CharField(blank=True, default='Espace des membres du Comité de lecture', max_length=220, verbose_name='Lien comité lecture (menu mobile)'),
        ),
    ]
