# Generated by Django 6.0.1 on 2026-02-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de crÃ©ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('meta_title', models.CharField(blank=True, help_text='Titre optimisÃ© pour les moteurs de recherche (max 60 caractÃ¨res)', max_length=60, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractÃ¨res)', max_length=160, verbose_name='Description SEO')),
                ('nom', models.CharField(db_index=True, help_text="Nom complet de l'auteur", max_length=200, verbose_name='Nom complet')),
                ('specialite', models.CharField(help_text='Genre littÃ©raire de prÃ©dilection (ex: Romans, PoÃ©sie)', max_length=100, verbose_name='SpÃ©cialitÃ©')),
                ('biographie', models.TextField(help_text="Biographie complÃ¨te de l'auteur", verbose_name='Biographie')),
                ('photo', models.ImageField(help_text="Photo de l'auteur (format recommandÃ© : 400x500px)", upload_to='authors/%Y/%m/', verbose_name='Photo')),
                ('slug', models.SlugField(blank=True, help_text='URL conviviale (gÃ©nÃ©rÃ© automatiquement)', max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='catalogue_a_nom_278a7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de crÃ©ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('meta_title', models.CharField(blank=True, help_text='Titre optimisÃ© pour les moteurs de recherche (max 60 caractÃ¨res)', max_length=60, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractÃ¨res)', max_length=160, verbose_name='Description SEO')),
                ('titre', models.CharField(db_index=True, max_length=300, verbose_name='Titre')),
                ('categorie', models.CharField(choices=[('roman', 'Roman'), ('poemes', 'PoÃ¨mes'), ('essai', 'Essai'), ('policiers', 'Policiers & Thrillers'), ('litterature-fr', 'LittÃ©rature franÃ§aise'), ('litterature-etr', 'LittÃ©rature Ã©trangÃ¨re'), ('beaux-livres', 'Beaux livres'), ('jeunesse', 'Jeunesse'), ('sh', 'Sciences humaines')], db_index=True, max_length=50, verbose_name='CatÃ©gorie')),
                ('collection', models.CharField(help_text='Nom de la collection Ã©ditoriale', max_length=100, verbose_name='Collection')),
                ('resume', models.TextField(help_text='RÃ©sumÃ© ou quatriÃ¨me de couverture', verbose_name='RÃ©sumÃ©')),
                ('isbn', models.CharField(db_index=True, help_text='NumÃ©ro ISBN unique', max_length=20, unique=True, verbose_name='ISBN')),
                ('prix', models.CharField(help_text="Prix au format texte (ex: '5000 FCFA')", max_length=50, verbose_name='Prix')),
                ('parution', models.DateField(db_index=True, verbose_name='Date de parution')),
                ('image', models.ImageField(help_text='Image de couverture (format recommandÃ© : 400x600px)', upload_to='books/%Y/%m/', verbose_name='Couverture')),
                ('lien_chariow', models.URLField(help_text="URL d'achat sur Chariow", max_length=500, verbose_name='Lien Chariow')),
                ('lien_amazon', models.URLField(help_text="URL d'achat sur Amazon", max_length=500, verbose_name='Lien Amazon')),
                ('lien_whatsapp', models.URLField(help_text='URL de commande WhatsApp', max_length=500, verbose_name='Lien WhatsApp')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug')),
                ('est_nouveau', models.BooleanField(db_index=True, default=False, help_text='Afficher dans les nouveautÃ©s', verbose_name='Est nouveau')),
                ('est_bestseller', models.BooleanField(db_index=True, default=False, help_text='Afficher dans les meilleures ventes', verbose_name='Est bestseller')),
                ('est_publie', models.BooleanField(db_index=True, default=True, help_text='Publier sur le site', verbose_name='Est publiÃ©')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livres', to='catalogue.auteur', verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-parution', '-created_at'],
                'indexes': [models.Index(fields=['titre', 'auteur'], name='catalogue_l_titre_5834a7_idx'), models.Index(fields=['-parution', 'categorie'], name='catalogue_l_parutio_9616da_idx'), models.Index(fields=['est_publie'], name='catalogue_l_est_pub_833ebb_idx')],
            },
        ),
    ]

