# Generated by Django 6.0.1 on 2026-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_livre_collection_alter_livre_lien_amazon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de crÃ©ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('poste', models.CharField(max_length=150, verbose_name='Poste/RÃ´le')),
                ('photo', models.ImageField(upload_to='team/%Y/%m/', verbose_name='Photo')),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie courte')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
            ],
            options={
                'verbose_name': "Membre de l'Ã©quipe",
                'verbose_name_plural': "Membres de l'Ã©quipe",
                'ordering': ['ordre_affichage', 'nom_complet'],
            },
        ),
        migrations.AddField(
            model_name='livre',
            name='est_prochaine_parution',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est prochaine parution'),
        ),
    ]

