# Generated by Django 6.0.1 on 2026-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_membre_livre_est_prochaine_parution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de crÃ©ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('meta_title', models.CharField(blank=True, help_text='Titre optimisÃ© pour les moteurs de recherche (max 60 caractÃ¨res)', max_length=60, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractÃ¨res)', max_length=160, verbose_name='Description SEO')),
                ('titre', models.CharField(max_length=250, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='news/%Y/%m/', verbose_name='Image')),
                ('extrait', models.TextField(max_length=300, verbose_name='Extrait')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Est publiÃ©')),
                ('est_une_a_la_une', models.BooleanField(default=False, verbose_name='Ã€ la une')),
            ],
            options={
                'verbose_name': 'ActualitÃ©',
                'verbose_name_plural': 'ActualitÃ©s',
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de crÃ©ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Inscription active')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Inscription Newsletter',
                'verbose_name_plural': 'Inscriptions Newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de crÃ©ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone')),
                ('sujet', models.CharField(max_length=250, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'TraitÃ©'), ('archive', 'ArchivÃ©')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date rÃ©ception')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('notes_admin', models.TextField(blank=True, verbose_name='Notes admin')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.AlterField(
            model_name='auteur',
            name='biographie',
            field=models.TextField(verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='nom',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='photo',
            field=models.ImageField(upload_to='authors/%Y/%m/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='specialite',
            field=models.CharField(max_length=100, verbose_name='SpÃ©cialitÃ©'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='collection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='est_bestseller',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est bestseller'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='est_nouveau',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est nouveau'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='est_publie',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Est publiÃ©'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(upload_to='books/%Y/%m/', verbose_name='Couverture'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='lien_amazon',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Amazon'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='lien_chariow',
            field=models.URLField(max_length=500, verbose_name='Lien Chariow'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='lien_whatsapp',
            field=models.URLField(max_length=500, verbose_name='Lien WhatsApp'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.CharField(max_length=50, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='resume',
            field=models.TextField(verbose_name='RÃ©sumÃ©'),
        ),
    ]

