# Generated by Django 5.0.1 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_actualite_inscriptionnewsletter_messagecontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionManuscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_complet', models.CharField(max_length=200, verbose_name="Nom et prénom à l'état civil")),
                ('nom_auteur', models.CharField(max_length=200, verbose_name="Nom ou pseudonyme d'auteur")),
                ('contacts', models.CharField(max_length=200, verbose_name='Contacts')),
                ('titre_ouvrage', models.CharField(max_length=300, verbose_name="Titre de l'ouvrage")),
                ('genre_litteraire', models.CharField(max_length=150, verbose_name='Genre littéraire')),
                ('synopsis', models.TextField(verbose_name='Synopsis ou résumé')),
                ('avantages', models.TextField(verbose_name='Avantages pour les lecteurs')),
                ('inconvenients', models.TextField(verbose_name='Inconvénients pour les lecteurs')),
                ('fichier_ouvrage', models.FileField(upload_to='soumissions/manuscrits/%Y/%m/', verbose_name="Fichier de l'ouvrage")),
                ('photo_auteur', models.ImageField(upload_to='soumissions/auteurs/%Y/%m/', verbose_name="Photo de l'auteur")),
                ('carte_identite', models.FileField(upload_to='soumissions/cartes/%Y/%m/', verbose_name="Carte d'identité")),
            ],
            options={
                'verbose_name': 'Soumission de manuscrit',
                'verbose_name_plural': 'Soumissions de manuscrits',
                'ordering': ['-created_at'],
            },
        ),
    ]
