# Generated by Django 5.0.1 on 2026-03-10 19:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_soumission_manuscrit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualite',
            options={'ordering': ['-date_publication', '-created_at'], 'verbose_name': 'Actualité', 'verbose_name_plural': 'Actualités'},
        ),
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ['ordre_affichage', 'nom_complet'], 'verbose_name': "Membre de l'équipe", 'verbose_name_plural': "Membres de l'équipe"},
        ),
        migrations.AlterField(
            model_name='actualite',
            name='contenu',
            field=ckeditor.fields.RichTextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='est_publie',
            field=models.BooleanField(default=True, verbose_name='Est publié'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='est_une_a_la_une',
            field=models.BooleanField(default=False, verbose_name='À la une'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='extrait',
            field=ckeditor.fields.RichTextField(max_length=300, verbose_name='Extrait'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre optimisé pour les moteurs de recherche (max 60 caractères)', max_length=60, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='biographie',
            field=ckeditor.fields.RichTextField(verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre optimisé pour les moteurs de recherche (max 60 caractères)', max_length=60, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='specialite',
            field=models.CharField(max_length=100, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='inscriptionnewsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('roman', 'Roman'), ('poemes', 'Poèmes'), ('essai', 'Essai'), ('policiers', 'Polars/Thrillers'), ('bd', 'BD'), ('theatres', 'Théâtres'), ('nouvelles', 'Nouvelles'), ('litterature-fr', 'Littérature française'), ('litterature-etr', 'Littérature étrangère'), ('beaux-livres', 'Beaux livres'), ('jeunesse', 'Jeunesse'), ('sh', 'Sciences humaines')], db_index=True, max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='est_publie',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Est publié'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre optimisé pour les moteurs de recherche (max 60 caractères)', max_length=60, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='resume',
            field=models.TextField(verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='biographie',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Biographie courte'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='poste',
            field=models.CharField(max_length=150, verbose_name='Poste/Rôle'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='date_reception',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date réception'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='notes_admin',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Notes admin'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='soumissionmanuscrit',
            name='avantages',
            field=ckeditor.fields.RichTextField(verbose_name='Avantages pour les lecteurs'),
        ),
    ]
