# Generated by Django 5.0.1 on 2026-03-10 19:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_actualite_options_alter_membre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('location', models.CharField(choices=[('header', 'En-tête'), ('footer', 'Pied de page')], default='header', max_length=20, verbose_name='Emplacement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Lien de menu',
                'verbose_name_plural': 'Liens de menu',
                'ordering': ['location', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('meta_title', models.CharField(blank=True, help_text='Titre optimisé pour les moteurs de recherche (max 60 caractères)', max_length=60, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Description SEO')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name="Titre d'en-tête")),
                ('hero_subtitle', models.CharField(blank=True, max_length=255, verbose_name="Sous-titre d'en-tête")),
                ('body', ckeditor.fields.RichTextField(verbose_name='Contenu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('show_team', models.BooleanField(default=False, verbose_name="Afficher l'équipe")),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
    ]
