# Generated by Django 5.0.1 on 2026-03-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_livre_auteurs_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixLitteraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom du prix')),
                ('annee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Prix littéraire',
                'verbose_name_plural': 'Prix littéraires',
                'ordering': ['-annee', 'titre'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS catalogue_l_titre_5834a7_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='livre',
                    name='catalogue_l_titre_5834a7_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS catalogue_l_titre_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS catalogue_l_titre_a73cdb_idx ON catalogue_livre (titre);",
                    reverse_sql="DROP INDEX IF EXISTS catalogue_l_titre_a73cdb_idx;",
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='livre',
                    new_name='catalogue_l_titre_a73cdb_idx',
                    old_name='catalogue_l_titre_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='image_audio',
            field=models.ImageField(blank=True, null=True, upload_to='books/audio/%Y/%m/', verbose_name='Couverture version audio'),
        ),
        migrations.AddField(
            model_name='livre',
            name='image_numerique',
            field=models.ImageField(blank=True, null=True, upload_to='books/numerique/%Y/%m/', verbose_name='Couverture version numérique'),
        ),
        migrations.AddField(
            model_name='livre',
            name='langue_publication',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('es', 'Espagnol'), ('pt', 'Portugais'), ('ar', 'Arabe')], db_index=True, default='fr', max_length=10, verbose_name='Langue de publication'),
        ),
        migrations.AddField(
            model_name='livre',
            name='lien_amazon_audio',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Amazon (audio)'),
        ),
        migrations.AddField(
            model_name='livre',
            name='lien_amazon_numerique',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Amazon (numérique)'),
        ),
        migrations.AddField(
            model_name='livre',
            name='lien_chariow_audio',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Chariow (audio)'),
        ),
        migrations.AddField(
            model_name='livre',
            name='lien_chariow_numerique',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Chariow (numérique)'),
        ),
        migrations.AddField(
            model_name='livre',
            name='lien_whatsapp_audio',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien WhatsApp (audio)'),
        ),
        migrations.AddField(
            model_name='livre',
            name='lien_whatsapp_numerique',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien WhatsApp (numérique)'),
        ),
        migrations.AddField(
            model_name='livre',
            name='version_audio',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Version audio disponible'),
        ),
        migrations.AddField(
            model_name='livre',
            name='version_numerique',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Version numérique disponible'),
        ),
        migrations.AddField(
            model_name='livre',
            name='version_papier',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Version papier disponible'),
        ),
        migrations.AddField(
            model_name='membre',
            name='nationalites',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez une ou plusieurs nationalités.', related_name='membres', to='catalogue.nationalite', verbose_name='Nationalités'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre optimisé pour les moteurs de recherche (max 60 caractères)', max_length=60, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(upload_to='books/%Y/%m/', verbose_name='Couverture version papier'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='lien_amazon',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Amazon (papier)'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='lien_chariow',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Chariow (papier)'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='lien_whatsapp',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien WhatsApp (papier)'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['nom', 'slug'], name='catalogue_c_nom_3a0d33_idx'),
        ),
        migrations.AddField(
            model_name='prixlitteraire',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prix_litteraires', to='catalogue.auteur', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='prixlitteraire',
            name='livre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prix_litteraires', to='catalogue.livre', verbose_name='Livre'),
        ),
    ]
