# Generated by Django 5.0.1 on 2026-03-12 14:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_seed_dynamic_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='langue_publication',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('de', 'Allemand'), ('ja', 'Japonais'), ('zh', 'Mandarin'), ('ru', 'Russe'), ('ar', 'Arabe'), ('fon', 'Fon'), ('yo', 'Yoruba'), ('ha', 'Haoussa'), ('sw', 'Swahili'), ('es', 'Espagnol'), ('pt', 'Portugais')], db_index=True, default='fr', max_length=10, verbose_name='Langue de publication'),
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('block_type', models.CharField(choices=[('rich_text', 'Texte libre'), ('image', 'Image'), ('cta', "Appel à l'action"), ('grid', 'Grille'), ('carousel', 'Carrousel'), ('stats', 'Statistiques'), ('team', 'Équipe'), ('contact_form', 'Formulaire de contact'), ('home_carousel', 'Accueil - Carrousel'), ('home_nouveautes', 'Accueil - Nouveautés'), ('home_bestsellers', 'Accueil - Meilleures ventes'), ('home_parutions', 'Accueil - Prochaines parutions'), ('home_actualites', 'Accueil - Actualités'), ('home_newsletter', 'Accueil - Newsletter')], max_length=40, verbose_name='Type de bloc')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('contenu', ckeditor.fields.RichTextField(blank=True, verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/blocks/%Y/%m/', verbose_name='Image')),
                ('bouton_texte', models.CharField(blank=True, max_length=120, verbose_name='Texte du bouton')),
                ('bouton_url', models.CharField(blank=True, max_length=300, verbose_name='URL du bouton')),
                ('css_class', models.CharField(blank=True, max_length=120, verbose_name='Classe CSS')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='catalogue.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Bloc de page',
                'verbose_name_plural': 'Blocs de page',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('contenu', ckeditor.fields.RichTextField(blank=True, verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/items/%Y/%m/', verbose_name='Image')),
                ('icone', models.CharField(blank=True, max_length=80, verbose_name="Classe d'icône (Font Awesome)")),
                ('lien_texte', models.CharField(blank=True, max_length=120, verbose_name='Texte du lien')),
                ('lien_url', models.CharField(blank=True, max_length=300, verbose_name='URL du lien')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.pageblock', verbose_name='Bloc')),
            ],
            options={
                'verbose_name': 'Élément de bloc',
                'verbose_name_plural': 'Éléments de bloc',
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
