# Generated by Django 5.0.1 on 2026-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_audioconversionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioconversionrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
