# Generated by Django 5.0.1 on 2026-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_alter_audioconversionrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioconversionrequest',
            name='paiement_initie_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paiement initié le'),
        ),
    ]
