# Generated by Django 5.0.1 on 2026-03-12 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_audioconversionrequest_paiement_initie_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audioconversionrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_conversions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='audioconversionrequest',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français')], default='fr', max_length=10, verbose_name='Langue'),
        ),
    ]
