# Generated by Django 5.0.1 on 2026-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_remove_soumissionmanuscrit_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionmanuscrit',
            name='nationalite',
            field=models.CharField(default='', max_length=120, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='soumissionmanuscrit',
            name='pays_residence',
            field=models.CharField(default='', max_length=120, verbose_name='Pays de résidence'),
        ),
    ]
