# Generated by Codex on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0032_soumissionmanuscrit_nationalite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioconversionrequest",
            name="voix_humaine",
            field=models.CharField(blank=True, choices=[("female", "Féminine"), ("male", "Masculine")], max_length=10, verbose_name="Voix humaine"),
        ),
        migrations.AddField(
            model_name="audioconversionrequest",
            name="voice_type",
            field=models.CharField(choices=[("synthetic", "Synthétique"), ("human", "Humaine")], default="synthetic", max_length=10, verbose_name="Type de voix"),
        ),
    ]
