# Generated by Django 5.0.1 on 2026-03-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_audioconversionchunk'),
        ('catalogue', '0032_soumissionmanuscrit_nationalite_and_more'),
    ]

    operations = [
    ]
