# Generated by Codex on 2026-03-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0033_audio_conversion_human_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("note", models.PositiveSmallIntegerField(verbose_name="Note (/20)")),
                ("observation", models.TextField(blank=True, verbose_name="Observation")),
                ("decision", models.CharField(choices=[("yes", "Oui"), ("no", "Non")], max_length=10, verbose_name="Décision")),
                ("reviewer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="manuscript_reviews", to=settings.AUTH_USER_MODEL, verbose_name="Évaluateur")),
                ("soumission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluations", to="catalogue.soumissionmanuscrit", verbose_name="Soumission")),
            ],
            options={
                "verbose_name": "Évaluation de manuscrit",
                "verbose_name_plural": "Évaluations de manuscrits",
                "ordering": ["-created_at"],
                "unique_together": {("soumission", "reviewer")},
            },
        ),
    ]
