# Generated by Django 5.0.1 on 2026-03-18 04:07
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0033_merge_20260318_0504"),
        ("catalogue", "0034_merge_20260318_0501"),
    ]

    operations = []
