# Generated by Django 5.0.1 on 2026-03-18 10:21
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0034_audioconversionrequest_lecture_humaine"),
        ("catalogue", "0035_merge_20260318_0507"),
    ]

    operations = []
