# Generated by Django 5.2.8 on 2026-03-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_add_meta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioConversionGenerated',
            fields=[
            ],
            options={
                'verbose_name': 'Audio généré',
                'verbose_name_plural': 'Audios générés',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalogue.audioconversionrequest',),
        ),
        migrations.AlterModelOptions(
            name='committeeapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidature comité de lecture', 'verbose_name_plural': 'Candidatures comité de lecture'},
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.AlterField(
            model_name='audioconversionrequest',
            name='langue',
            field=models.CharField(choices=[('auto', 'Auto (détection)'), ('fr', 'Français'), ('en', 'Anglais'), ('de', 'Allemand'), ('ja', 'Japonais'), ('zh', 'Mandarin'), ('ru', 'Russe'), ('ar', 'Arabe'), ('fon', 'Fon'), ('yo', 'Yoruba'), ('ha', 'Haoussa'), ('sw', 'Swahili'), ('es', 'Espagnol'), ('pt', 'Portugais')], default='fr', max_length=10, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='committeeapplication',
            name='confidentiality_ack',
            field=models.BooleanField(default=False, verbose_name='Accord confidentialité'),
        ),
        migrations.AlterField(
            model_name='committeeapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='committeeapplication',
            name='unpaid_ack',
            field=models.BooleanField(default=False, verbose_name='Mission non rémunérée acceptée'),
        ),
        migrations.AlterField(
            model_name='committeeapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
