# Generated by ChatGPT on 2026-04-01

from django.db import migrations, models
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0044_actualite_meta_keywords_auteur_meta_keywords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="biographie_longue",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Biographie détaillée"),
        ),
        migrations.AddField(
            model_name="membre",
            name="telephone",
            field=models.CharField(blank=True, max_length=40, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="membre",
            name="site_web",
            field=models.URLField(blank=True, verbose_name="Site web"),
        ),
        migrations.AddField(
            model_name="membre",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="membre",
            name="facebook",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="membre",
            name="x_twitter",
            field=models.URLField(blank=True, verbose_name="X (Twitter)"),
        ),
        migrations.AddField(
            model_name="membre",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="membre",
            name="tiktok",
            field=models.URLField(blank=True, verbose_name="TikTok"),
        ),
        migrations.AddField(
            model_name="membre",
            name="youtube",
            field=models.URLField(blank=True, verbose_name="YouTube"),
        ),
        migrations.AddField(
            model_name="membre",
            name="whatsapp",
            field=models.URLField(blank=True, verbose_name="WhatsApp"),
        ),
    ]
