# Generated by ChatGPT on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0046_normalize_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="auteur",
            name="prefixe",
            field=models.CharField(blank=True, max_length=30, verbose_name="Préfixe (Dr, Pr, Prof...)"),
        ),
        migrations.AddField(
            model_name="membre",
            name="prefixe",
            field=models.CharField(blank=True, max_length=30, verbose_name="Préfixe (Dr, Pr, Prof...)"),
        ),
    ]

