# Generated by Django 5.2.8 on 2026-04-01 20:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_add_prefix_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='resume',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Résumé'),
        ),
    ]
