# Generated by Django 5.2.8 on 2026-04-01 20:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_alter_livre_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptreview',
            name='observation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='prixlitteraire',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='soumissionmanuscrit',
            name='inconvenients',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Inconvénients pour les lecteurs'),
        ),
        migrations.AlterField(
            model_name='soumissionmanuscrit',
            name='synopsis',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Synopsis ou résumé'),
        ),
    ]
